Some enhancement for tomcat-all cookbook. * Remove ['tomcat-all']['install_directory'] : just let use ark's default home directory which is `/usr/local`. I believe we can use ark home directory attribute if we want to change the install directory. * Add tomcat major version postfix on service name. init.d script name will be `/etc/init.d/tomcat7` if `['tomcat-all']['version']` is stared with `7` * Use `setenv.sh` instead of `catalina.sh`(catalina.conf.erb) for setting environment variable : using setenv.sh file is preffered from apache tomcat. * Add service with subscribes to restart the tomcat when some restarting required file has changed. * Add empty catalina.pid file to prevent error when first restarting (actually start) for tomcat. * Clear Rubocop offenses. * Clear Foodcritic violations.

diff --git a/templates/default/init.conf.erb b/templates/default/init.conf.erb
--- a/templates/default/init.conf.erb
+++ b/templates/default/init.conf.erb
@@ -9,53 +9,49 @@
 . /etc/init.d/functions
 
 TOMCAT_USER=<%= node['tomcat-all']['user'] %>
-CATALINA_HOME=<%= node['tomcat-all']['install_directory'] %>/tomcat
+CATALINA_HOME=<%= node['tomcat-all']['tomcat_home'] %>
 CATALINA_PID=$CATALINA_HOME/catalina.pid
-RETVAL=$?
 
 case "$1" in
 start)
-        echo "Starting Tomcat"
-        exec su -l $TOMCAT_USER -c "$CATALINA_HOME/bin/catalina.sh start"
+    echo "Starting Tomcat"
+    exec su $TOMCAT_USER -c "$CATALINA_HOME/bin/catalina.sh start"
 ;;
 
 stop)
-        echo "Stopping Tomcat"
-        exec su -l $TOMCAT_USER -c "$CATALINA_HOME/bin/catalina.sh stop -force"
+    echo "Stopping Tomcat"
+    exec su $TOMCAT_USER -c "$CATALINA_HOME/bin/catalina.sh stop -force"
 ;;
 
 restart)
-        $0 stop
-        sleep 15
-        $0 start
+    $0 stop
+    sleep 15
+    $0 start
 ;;
 
 status)
-if [ -f "$CATALINA_PID" ]; then
-    pid=`cat "$CATALINA_PID"`
-    if [ "$pid" != "" ]; then
-                if [ -d /proc/$pid ]; then
-			# Process is running
-			ISRUNNING="1"
-    			echo "Tomcat is running with pid $pid"
-			exit 0
-		else 
-			echo "Tomcat not running (removing stalled PID file)" 
-			rm -f "$CATALINA_PID"
-			exit 1
-		fi
-	fi
-  else
-    echo "Tomcat is not running (or $CATALINA_PID is missing)"
-    exit 1
- fi
-
+    if [ -f "$CATALINA_PID" ]; then
+        pid=`cat "$CATALINA_PID"`
+        if [ "$pid" != "" ]; then
+            if [ -d /proc/$pid ]; then
+                # Process is running
+                ISRUNNING="1"
+                echo "Tomcat is running with pid $pid"
+                exit 0
+            else
+                echo "Tomcat not running (removing stalled PID file)"
+                rm -f "$CATALINA_PID"
+                exit 1
+            fi
+        fi
+    else
+        echo "Tomcat is not running (or $CATALINA_PID is missing)"
+        exit 1
+    fi
 ;;
 
 *)
-        echo $"Usage: $0 {start|stop|restart|status}"
-        exit 1
+    echo $"Usage: $0 {start|stop|restart|status}"
+    exit 1
 ;;
 esac
-
-exit $RETVAL
